language: python

sudo: false
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8-dev

install:
  - pip install pyflakes pytest

script:
  - set -x
  - pyflakes .
  - python -We::SyntaxWarning -m compileall -f -q mypython/
  - pytest
  # Make sure it installs
  - python setup.py install
